#ifndef H_MANDELBROT_CONSTANTS
#define H_MANDELBROT_CONSTANTS

#define DEFAULT_UNDEFINED 0L

#define DEFAULT_IMAGE_WIDTH 1024
#define DEFAULT_IMAGE_HEIGHT 768
#define DEFAULT_ITERATIONS 50

#define DEFAULT_THREADS DEFAULT_UNDEFINED

#define DEFAULT_PLOT_X    -0.75
#define DEFAULT_PLOT_Y     0.00
#define DEFAULT_PLOT_ZOOM  300

#define DEFAULT_VERBOSE false

#define DEFAULT_FILENAME "out.png"

#endif

