#ifndef __H_CONSTANTS
#define __H_CONSTANTS

#define DEFAULT_UNDEFINED -1 

#define DEFAULT_IMAGE_WIDTH 1024
#define DEFAULT_IMAGE_HEIGHT 768
#define DEFAULT_ITERATIONS 200

#define DEFAULT_THREADS DEFAULT_UNDEFINED

#define DEFAULT_PLOT_REAL_X1 -2.25
#define DEFAULT_PLOT_REAL_X2  1.25
#define DEFAULT_PLOT_IMAG_Y1 -1.25
#define DEFAULT_PLOT_IMAG_Y2  1.25

#define DEFAULT_VERBOSE false

#define DEFAULT_FILENAME "out.png"

#endif

